version: '3.8'

services:
  app:
    container_name: opendata-kuburaya
    image: mrdiio/opendata-kuburaya
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5000:80'
